### ISSUE TITLE
Set up continuous integration on CircleCI

### ISSUE THREAD

**Issue by andersy005** [maboualidev/TimeAxis#1]
@maboualidev, do you mind registering this repo on CircleCI: https://circleci.com/setup-project/gh/maboualidev/TimeAxis ? I am thinking of setting up continuous integration for this repo but the repo admin needs to activate the repo on CircleCI.  Once the setup on CircleCI, I will add the necessary configuration to the repo.

**Comment by andersy005** [comment]
Closing this issue as it appears that it was addressed over recently.

**Comment by maboualidev** [comment]
@andersy005 
Hi Anderson,

I added the repo to the CircleCI + CodeCov and added some basic scripts. Please have a look and make appropriate changes as you deem fit.

Also, I am trying to add you as Admin to the repo. But it seems I am not able to do it. I think maybe because it is in a personal repo and not part of an organization. Do you have any idea?

**Comment by andersy005** [comment]
> Also, I am trying to add you as Admin to the repo. But it seems I am not able to do it. I think maybe because it is in a personal repo and not part of an organization.

This is correct. It appears that repos hosted under personal account behave differently from repos in an organization. If you don't mind, we can transfer the repo to the NCAR org
